# Generated by Django 3.1.7 on 2021-02-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrives',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
