# Generated by Django 3.1.7 on 2021-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientpage', '0003_auto_20210227_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrives',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationdrives',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationdrives',
            name='timeclose',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationdrives',
            name='timeopen',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
